arb-dir: lib/l10n
template-arb-file: app_fr.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: ["fr"]
synthetic-package: false
nullable-getter: false
use-deferred-loading: false
