name: shayniss
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  image_picker: ^1.0.5
  image_picker_for_web: ^3.0.1
  flutter_secure_storage: ^9.0.0
  flutter_secure_storage_web: ^1.1.2
  shared_preferences_web: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
