name: shayniss
description: Application de beauté et bien-être à domicile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.6.0
  go_router: ^13.0.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  google_maps_flutter_web: ^0.5.4+2
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  flutter_secure_storage: ^9.0.0
  flutter_secure_storage_web: ^1.1.2
  shared_preferences_web: ^2.2.2
  card_swiper: ^3.0.1
  cached_network_image: ^3.3.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator_web: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/services/
    - assets/images/profile/
    - assets/images/gallery/
    - assets/images/default/
